# Database configuration
connection:
  dialect: postgresql
  driver: psycopg2
  username: DB_User_Here
  password: DB_Password_Here
  host: localhost
  port: 5432
  database: trading_bot_db

schema:
  trades_table: trades
  positions_table: positions
  performance_table: performance

migrations:
  directory: migrations/
