# Trading Environment Configuration

# Risk Management Settings
risk_profile: medium
max_drawdown: 0.20
position_sizing:
  risk_percentage: 2
  stop_loss_pips: 50

# Data Settings
data_source: polygon
stock_tickers:
  - AAPL
  - GOOG
  - MSFT

# Model Settings
model_type: LSTM
hyperparameters:
  learning_rate: 0.001
  hidden_units: 50
  batch_size: 64
  epochs: 100

# Backtesting Settings
backtest_ratio: 0.8
walk_forward_window: 30
optimization_iterations: 50

# Performance Metrics
metrics:
  - MSE
  - Sharpe Ratio
  - Win Rate
  - Drawdown

# Logging Settings
log_level: INFO
log_file: trading_bot.log

# API Settings
polygon_api_key: ${POLYGON_API_KEY}
news_api_key: ${NEWS_API_KEY}
